### ISSUE TITLE
Feature Request: Event locations to accept an address

### ISSUE THREAD

**Issue by ruzz311** [mikeal/gatherbugs#11]
When trying to pick a location, I was not able to enter an address.  I've worked with google's places API before and it seems like maybe you're only giving back a sub-set of  place "types".  If there could be a maps API look up for an address as well.  House party!

**Comment by mikeal** [comment]
we're using the Foursquare API, not Google Places. Places comes with a variety of restrictions on what you can do with the data but the 4sq API notably misses this feature.

**Comment by ruzz311** [comment]
[Path](https://path.com/) restricts android where you can't enter a custom location and I think it really hurts the experience since you're only limited to the pool of locations created by iOS users / whatever location discovery API they use.

**Comment by max-mapper** [comment]
I definitely want to enable house parties!

On the location results page we could show a 'This is an address' button for the user to click to geocode their input or something rather than forcing them to find a matching foursquare venue

**Comment by max-mapper** [comment]
coming soon to a release near you:
![](http://i.imgur.com/kzPQe.png)
doesn't do address lookups yet but you can put the address in the comments/description
