### ISSUE TITLE
Android: Can't seem to enter location

### ISSUE THREAD

**Issue by apage43** [mikeal/gatherbugs#13]
Trying to set the "Where?" on an event.

Android 4.1.1 - Galaxy Nexus

![where](http://drop.crate.im/where.png)

![where-entry](http://drop.crate.im/where-entry.png)

It's possibly a bug and not displaying something. (Nothing happens if I start typing either)

**Comment by max-mapper** [comment]
whoa weird. I was experiencing weiiirddd issues with focus and onkeyup events on android. I'll have to dig into this further. thanks for the report

**Comment by joannewong** [comment]
i thought this was happening as well, but if i waited long enough, venues would finally show up. HTC One X / Android 4.0.3.

**Comment by apage43** [comment]
Hm. It'll actually search on the latest one if I explicitly hit the "Go" button on the keyboard. Perhaps make it check if the field has changed anytime the keyboard is closed.
