### ISSUE TITLE
Android: "Following" shows events from people I am not following when connected to Twitter.

### ISSUE THREAD

**Issue by joannewong** [mikeal/gatherbugs#15]
When I click to the events they also show an "Unfollow" button, but I neither follow them on Twitter nor followed their event.

**Comment by max-mapper** [comment]
@mikeal can explain this

**Comment by mikeal** [comment]
can you tell me what the events are and I'll try to figure it out?

**Comment by joannewong** [comment]
@apage43 
lunch outta some trailer
about 3 hours ago

@pouchtest 
oioiiiiii
No time set

@pouchtestfoooooo
No time set

(etc. a whole bunch from @pouchtest)

**Comment by mikeal** [comment]
hrm.....

**Comment by mikeal** [comment]
GOOD BUG!

Fixed and deployed. Our query on import wasn't bounded correctly.

You'll need to unfollow the events you have in your view as this only happens at import time. It is now fixed for new users though :)

**Comment by joannewong** [comment]
hurrah, thanks!

**Comment by max-mapper** [comment]
+10 maxpoints for jo. they can be redeemed for coffee at coffee shops in oakland in my presence

**Comment by joannewong** [comment]
hm, i just got a new event from @pouchtest. is that still supposed to happen?

**Comment by mikeal** [comment]
that is super weird....

**Comment by max-mapper** [comment]
@mikeal make sure you're using redis correctly :)
