### ISSUE TITLE
Android: Battery usage way too high

### ISSUE THREAD

**Issue by cramforce** [mikeal/gatherbugs#18]
I started the app today, clicked around a bit and then put it in the background.
My battery drained significantly faster than it used to and the system stats show gather used 25% of the power.

**Comment by apage43** [comment]
It looks like this may be being caused by the app constantly reading the gyro/orientation sensor.

**Comment by mikeal** [comment]
we should only be doing that when the app is in the foreground. how are doing that when it's in the background?

**Comment by cramforce** [comment]
In android background apps can still do everything as in real multitasking.
Should be easy to detect.
On Jul 19, 2012 12:03 PM, "Mikeal Rogers" <
reply@reply.github.com>
wrote:

**Comment by max-mapper** [comment]
ahahaha oops, good call @apage43!

**Comment by max-mapper** [comment]
this should be fixed in the newest version posted on downloads

https://github.com/mikeal/gatherbugs/downloads
