### ISSUE TITLE
can't pick day/month on android, only hour/minute

### ISSUE THREAD

**Issue by max-mapper** [mikeal/gatherbugs#2]

**Comment by AaronAmstutz** [comment]
Also, hour/minute is in 24 hour time, European or military in the US. Maybe tie into user's location to decide which format to show it in?

**Comment by AaronAmstutz** [comment]
Also also, on android 4.0.3 all time is in the past, maybe because date isn't visible/included, therefore events that I create don't show up in following or nearby?

**Comment by AaronAmstutz** [comment]
Also also also, maybe its just because I'm in Portland and my events are already in the past?

**Comment by apage43** [comment]
Seems the time chosen is always on the current day, so if you set the time to 12:00 Noon and it's already 3PM, you'll get 3 hours ago.

These time and date picker dialogs are available in Android 3.0+ (And there's a support library that will pull them in, which I believe is installable via the SDK manager, for versions older than 3.0); http://developer.android.com/guide/topics/ui/controls/pickers.html

**Comment by cramforce** [comment]
/subscribe
Happens to me, too :(

**Comment by mbrochh** [comment]
Planning gatherings for upcoming days would be awesome. hour/minute for current day is not sufficient.

**Comment by jswartwood** [comment]
+9999 This one basically makes the app useless near the end of a day :(

**Comment by max-mapper** [comment]
this will be fixed soon!
