### ISSUE TITLE
Android: Pressing notification does nothing

### ISSUE THREAD

**Issue by apage43** [mikeal/gatherbugs#20]
I got a notification about an event, but I couldn't do anything with it. It should open the event in question, or something like that.

![](http://drop.crate.im/2012-07-19_15.27.47-20120719-153033.png)

**Comment by apage43** [comment]
It's also worth mentioning that the event I was being notified about also didn't appear in my events list, even after refreshing

**Comment by max-mapper** [comment]
@apage43 would you mind refreshing again and seeing if the event showed up now?

**Comment by apage43** [comment]
I see it now.

**Comment by mikeal** [comment]
i think you were literally **right** on the border of 31 miles from that event and moving around even a little was putting it out of bounds. after some discussion, we realized it was better to increase the radius to 50 miles.
