### ISSUE TITLE
Android: I think you are asking for too many permissions (All of them?)

### ISSUE THREAD

**Issue by cramforce** [mikeal/gatherbugs#21]
While you don't want to add them too often (as that makes updates non-automatic), you should still start with the absolute minimum.

**Comment by mikeal** [comment]
sorry Malte, we need all of your personal data for sketching marketing :)

j/k

i think this is just the default phonegap permissions list, will fix soon.

**Comment by max-mapper** [comment]
fixed this, now it only asks for 5 things (location and internet mostly)

**Comment by ruzz311** [comment]
I had this same concern a with the first version I installed(beta 1).  I just [downloaded the latest release (beta3)](https://github.com/mikeal/gatherbugs/downloads) and Gather is still requesting 8 permissions.  

Specifically, I'm concerned with:
-    Read/Write contact info (mostly concerned with _write_)  
-    Receive SMS  
-    Phone calls  
-    System Tools (prevent phone from sleeping)  

Is beta 3 the release with less permissions or am I missing something?

**Galaxy Nexus 4.0.3**

**Comment by mikeal** [comment]
Max was referring to what is now in the Google Play store. Is that still asking for all these permissions?

**Comment by ruzz311** [comment]
Nope - I've been out of the loop for a couple of days.  Do you want bugs reported from the official app now or would you like input on the beta versions still?

**Comment by mikeal** [comment]
Our latest is on the Play store, please log those bugs here.

**Comment by ruzz311** [comment]
Will do - thanks!
