### ISSUE TITLE
Android: Push notification not clickable

### ISSUE THREAD

**Issue by cramforce** [mikeal/gatherbugs#22]
I just got a notification (hopefully via push) about an event change, but when I touch it, nothing happens. I want to be taken to the details of the event in the app.

**Comment by mikeal** [comment]
we have another issue on this already.

**Comment by cramforce** [comment]
Sorry

**Comment by max-mapper** [comment]
dont be sorry malte! you are a good beta tester!

**Comment by max-mapper** [comment]
for every issue you open I will buy you some unit of food or drink worth at least $3 USD
