### ISSUE TITLE
not available on my device (Galaxy Nexus?)

### ISSUE THREAD

**Issue by gflarity** [mikeal/gatherbugs#25]
"This app is incompatible with all of your devices." I have a Galaxy Nexus. This may just be a country issue in disguise though. I'm in Canada. You should make it available there if it's not really supported. Want to check it out :)

**Comment by mikeal** [comment]
Our test devices are Galaxy Nexuses so it's definitely not a device or OS issue.

@maxogden does the Play store have a bunch of check boxes for countries like the iOS App Store?

**Comment by mattpardee** [comment]
I have this same issue for Nexus 7. But I'm in 'merica

**Comment by mikeal** [comment]
yeah, that's because we haven't built a tablet version yet :)

ordering devices :)

**Comment by mikeal** [comment]
ordered a Nexus 7 and an ancient unlocked Android 2.2 phone from LG.

**Comment by benatkin** [comment]
Mine is a 2.2 LG. Glad you ordered one, but I won't blame you if you decide it isn't worth the trouble.

**Comment by benatkin** [comment]
I should be able to use it on my iPod Touch, though!

**Comment by mikeal** [comment]
iPod Touch will work with iOS 5.1

we need to get it working on Android 2.2 though, it's the lions share of the Android market.

**Comment by benatkin** [comment]
I see...guess that's why most apps work on my phone, despite it being old.

Looking forward to using it for Boulder JS.

**Comment by max-mapper** [comment]
it should be available in all countries and all devices that run 4.0 or above, if not then its probably a google play caching error

**Comment by max-mapper** [comment]
you should be able to install it from the play store now on any device 4.0 or above
