### ISSUE TITLE
Facebook Timeline Entry

### ISSUE THREAD

**Issue by euforic** [mikeal/gatherbugs#29]
Facebook time line entry should show gather.at logo and map image maybe but i got this 
![gather](http://f.cl.ly/items/1V2n2O0N1b1D163h160G/Screen%20Shot%202012-07-20%20at%201.21.43%20PM.png)

Otherwise great APP!!!

**Comment by mikeal** [comment]
probably an opengraph issue. i'll investigate, thanks :)

**Comment by mikeal** [comment]
alright, i added the open graph properties for an "article".

@maxogden I still need you to fill in an image url, don't know exactly how we can do that since the map we do we overlay some stuff in javascript.
