### ISSUE TITLE
Clicking an event in "Nearby" gives blank screen

### ISSUE THREAD

**Issue by strathmeyer** [mikeal/gatherbugs#30]
Well, mostly blank. There is a green bar at the top with a silver Back button in the upper left, but no other text or UI elements on the page.

Repro steps:
- load the app
- click the Nearby tab at the bottom right
- click on one of the events

Clicking on events in Following works fine. I have tried restarting the app. Same result.

Environment: iOS 5.1.1 (9B206), iPhone 4S

**Comment by mikeal** [comment]
Are they events from people you do not follow or people that you happen to follow that also post something nearby?

**Comment by strathmeyer** [comment]
Nearby only shows me events from people I dont follow. There are actually some events in the Following tab which are closer than the events in the Nearby tab, but they are not shown in Nearby.

**Comment by mikeal** [comment]
did those events start in the past?

in following we show events that started up to 3 hours ago. in nearby we only show from now in to the future.

**Comment by strathmeyer** [comment]
No, all Following events happen in the future. (it's you, Max, and Jlord). 

Okay, I just checked again and things are getting weirder. The dinner JS event you just posted is now showing up in nearby. However none of the other following events are showing up in nearby. If I click on your new dinner JS event in nearby it shows the correct info. Other events in nearby still show the blank page.

**Comment by mikeal** [comment]
the bounding box for nearby is much smaller than following.

this is what I think the bug is: we're pulling data from the cache for detail and we don't have a cache for nearby we only have the data returned from the API call.

the events from people you follow are in cache so they show up.

@maxogden does that sound about right?

**Comment by stephenhandley** [comment]
that sounds right i'm seeing non-followed events blank but dinner.js is fine
Food trucks at Fort Mason
dinner.js
Phono del Sol
Help us move a bed

**Comment by johnmdonahue** [comment]
Same here. I can only view event details of people I follow, otherwise a blank screen, and crashes after repeated attempts to view details.

iOS 5.1.1 (9B206), iPhone 4

**Comment by mikeal** [comment]
fix is waiting for app store approval.

should be fixed on latest Android.
