### ISSUE TITLE
'Following' & Show Nav buttons not working

### ISSUE THREAD

**Issue by jorydotcom** [mikeal/gatherbugs#31]
Tapping either button just refreshes the screen rather than taking me to the nav. I'm on an iPhone 4 w/ IOS 5.1.1.

**Comment by mikeal** [comment]
i think this might actually be https://github.com/mikeal/gatherbugs/issues/26

**Comment by jorydotcom** [comment]
Possible, but the issue I'm having is:
- Tapping the show nav button either refreshes or crashes the app
- Tapping the following button doesn't do anything

I've uninstalled & reinstalled the app - Let me know if you need any more info.  Love what you're doing though!! Thanks @mikeal  & @maxogden !!

**Comment by mikeal** [comment]
the following/nearby buttons are basically tabs. we should do a better job of surfacing the states.

the top buttons swap between the list view and the map view.

the crash I believe we are tracking here: https://github.com/mikeal/gatherbugs/issues/24

unfortunately @maxogden can't reproduce it on our phones.

**Comment by jorydotcom** [comment]
ah ok. I think this is a case of me not getting the ui. gracias!

**Comment by mikeal** [comment]
this is good feedback though. this stuff should all be more obvious.

the crash is very concerning, we are tracking it down.
