### ISSUE TITLE
open source your software

### ISSUE THREAD

**Issue by indutny** [mikeal/gatherbugs#32]
Release some source? ;)

**Comment by mikeal** [comment]
we already have :) 

http://www.mikealrogers.com/posts/open-source.html

**Comment by max-mapper** [comment]
see also:
http://blip.tv/jsconfar/max-ogden-making-native-feeling-html5-apps-for-ios-6228868
http://maxogden.com/fast-webview-applications
http://github.com/maxogden/viewkit
