### ISSUE TITLE
Android : Twitter avatars in list view repeat vertically 

### ISSUE THREAD

**Issue by filmaj** [mikeal/gatherbugs#37]
On  a Samsung galaxy nexus running 4.0.4.

When i open the list view, my Twitter contacts that create a gathering have their avatars "repeat" vertically. As if the image does not fill up the entire size of the image container. 

On my phone right now so can't take a screenshot - will try to get you one in a bit.

**Comment by filmaj** [comment]
Here we go.

![twitter avatar bug](http://i.imgur.com/UpsxJ.png)

**Comment by mikeal** [comment]
I see this on iPhone sometimes too. 

## 

Mikeal Rogers
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by apage43** [comment]
Incidentally, you should be able to screenshot on the nexus with power+vol down.

**Comment by max-mapper** [comment]
good call -- i should vertically center the avatar if its not square and set it to not tile
