### ISSUE TITLE
map is distorted on nexus7

### ISSUE THREAD

**Issue by max-mapper** [mikeal/gatherbugs#4]
![](http://i.imgur.com/SBoWe.png)

doesnt happen on galaxy nexus

**Comment by apage43** [comment]
I actually did see this kind of tearing for a bit on my nexus, playing around, but it righted itself. If you can reproduce the issue in the Chrome app with a similar bit of HTML or something, you can use remote debugging to poke at it; https://developers.google.com/chrome/mobile/docs/debugging

**Comment by ruzz311** [comment]
I'm not sure if I'm supposed to be able to zoom in and out of the map.  I sometimes can see a zoom out icon but not always.  The zoom icon seems to be behind the map until the map tiles load and cover it again - I believe this is the tearing you speak of.

[screen-capture right after moving the map](https://www.dropbox.com/s/hc8lg2dqziyvzxr/Screenshot_2012-07-18-02-52-28.png)

**Comment by max-mapper** [comment]
@ruzz311 @apage43 @feinbergscott if you get a chance could you try beta 2 from https://github.com/mikeal/gatherbugs/downloads ? I updated the mapping library i'm using which hopefully fixes some of the bugs mentioned here

there is also a known webkit bug that gets exacerbated by this mapping lib to cause crashing, more info here https://github.com/mikeal/gatherbugs/issues/14

**Comment by max-mapper** [comment]
ok I JUST uploaded a second copy of beta 2 that hopefully fixes the crashing bug

https://github.com/CloudMade/Leaflet/issues/137#issuecomment-7082502

if anyone can get the map to crash gather lemme know

**Comment by max-mapper** [comment]
fixed this earlier, it was a weird android browser bug
