### ISSUE TITLE
Only able to Auth one network on app init?

### ISSUE THREAD

**Issue by AaronAmstutz** [mikeal/gatherbugs#5]
Running android 4.0.3 on AT&T Galaxy S2 (phone).
After initial startup screen, where auth happens with fb or twitter, there's no option that I can find to auth with the other. In my case I twitter auth'ed, and then realized that I might have fb friends that were using the app. My first reaction, which I think is probably pretty intuitive, is to hit the settings button (galaxy s2 has 4 pseudo-physical buttons) to bring up app settings so I could edit my account and add FB as an auth'ed network. 

Possibly a good UX reaction?

**Comment by mikeal** [comment]
click on any event you are following and there will be "tweet" and "facebook" icons which drop you in to the auth flow if you haven't auth'd yet.

you can get the same in the "create" page.

**Comment by AaronAmstutz** [comment]
Cool, just saw that.  Sorry, maybe invalid issue.

**Comment by mikeal** [comment]
it's still good feedback.

right now we don't have a setting UI (trying to avoid it) but there are a few things like this where it's the first place people want to look for stuff like this.

**Comment by AaronAmstutz** [comment]
Yeah, I totally understand not having one. But, hmm, I bet the percentage of users who would look there first is actually kind of low-ish. Most would assume that one auth is what they get, and would wait til the create/share state to auth with the other.  You're totally on track.

**Comment by nickpoorman** [comment]
+1 I was looking for the same thing, thinking it would be under a settings feature.
