### ISSUE TITLE
scared to press the unfollow button

### ISSUE THREAD

**Issue by mbrochh** [mikeal/gatherbugs#50]
I ASSUME that it would just block that user's gathers in the app, but who knows... it MIGHT unfollow those people on twitter / Facebook which of course would be a scandal. Unfortunately I have no good idea how to explain what that button does without cluttering the UI :(

**Comment by mikeal** [comment]
we should find a way to make it more explicit that you're only unfollowing the event.

**Comment by mbrochh** [comment]
oh wow now I am even more confused. Why would I want to unfollow events? Other than popping up in my list of events they don't generate any content, do they? Is it to clean up the list of events in case it is very long? Tho the unfollow button is the equivalent of "I'm not going and and not interested in this event"?

Maybe it would be better to have three buttons: Going, Maybe, Not going. When you press Not going, a dialogue asks you, if you also want to remove this event from your map / list.

**Comment by mikeal** [comment]
when they change, you get a push notification, unfollowing takes them out of your following feed and unsubscribes you from further notifications.

**Comment by max-mapper** [comment]
the more we talk about it the more I think something along the lines of "i'm definitely not going" or a "i'm definitely going" would be nice

**Comment by max-mapper** [comment]
changed the 'unfollow' button to 'ignore'
