### ISSUE TITLE
Cannot set time

### ISSUE THREAD

**Issue by mbrochh** [mikeal/gatherbugs#53]
A few weeks ago the app introduced a bug where I cannot set the time of the event any more.
After selecting a time from the time picker it always shows up as "NaN years ago".

I'm on Galaxy Nexus, Jelly Beans.

This is a show stopper. With this bug the app is completely unusable. :(

**Comment by max-mapper** [comment]
Have you tried the new beta? https://github.com/mikeal/gatherbugs/downloads it has a ton of small fixes

**Comment by mbrochh** [comment]
Ok with that version it works. You guys should release that ASAP :) Not all users will be active on Github :)
