### ISSUE TITLE
Date/Time/Where broken

### ISSUE THREAD

**Issue by gaak99** [mikeal/gatherbugs#54]
Android version released yesturday.

Running  on Android 4.0.4 galaxy nexus.

Touching Date or Time totally unresponsive.

 Touching Where does weird things.

 Totally unusable.

**Comment by max-mapper** [comment]
thanks for the report! I have tested on a 4.1 galaxy nexus and it works as expected. i'll see if I can get a 4.0.4 emulator

**Comment by gaak99** [comment]
Very curious to see how it goes for you on 4.0.4.

The previous version of app worked fine.

Thanks.

**Comment by gaak99** [comment]
Just tested the new version, works good. Thanks!

Let me know if i need to Close the bug or whatnot.
