### ISSUE TITLE
manual location input

### ISSUE THREAD

**Issue by jancborchardt** [mikeal/gatherbugs#55]
When you don’t have GPS enabled, there’s the error:
»GPS Error: Make sure location services are enabled on your phone.« (on Android)

In addition to the notice, it should be possible to manually input your location.

**Comment by max-mapper** [comment]
I fixed this but it isn't released yet

**Comment by jancborchardt** [comment]
![Cat’s usually don’t use GPS](http://vintageholidaycrafts.com/wp-content/uploads/2009/01/vintage-cat-clipart-cat-teaching-kittens-with-globe.jpg)
Thanks Max
