### ISSUE TITLE
Unable to create new gathering -  Android on Galaxy S3

### ISSUE THREAD

**Issue by nicdaCosta** [mikeal/gatherbugs#57]
I am using a Samsung Galaxy S3 with the stock rom (_android version 4.0.4_). When i open the app and try and select the cross/icon to add a new gathering, nothing happens. I am no longer taken to the create screen where as previously (before the latest update) i was.

I doubt that this is of any significance, but there are no current/upcoming gatherings displaying in the list when I try and create a new gathering.

I have managed to test this on another Galaxy S3, also running the stock rom, and experienced the same results.

**Comment by max-mapper** [comment]
thanks for the report! i'll add the galaxy S3 to my amazon shopping cart

**Comment by nicdaCosta** [comment]
i have just tested on my tablet (Samsung Galaxy tab 7.7) with stock rom (v 3.2) and i have found the same issue. also, once i select the nearby option, i am unable to select the following option. i have to use the back button.

if there is anyway for me to run further tests of any kind that can give u more info, will be glad to assist.

**Comment by nicdaCosta** [comment]
I can now create gathers on my S3 with the latest update. Thanks :)
