### ISSUE TITLE
Can't set start time in mobile browser on iOS

### ISSUE THREAD

**Issue by chesles** [mikeal/gatherbugs#64]
Tapping the "When?" input flashes yellow then returns to its initial state.

Browsers tested: latest Safari and Chrome for iOS.

Safari's "debug console" displays a javascript error `TypeError: 'undefined' is not an object` after tapping the "when?" input.

**Comment by max-mapper** [comment]
ooooh thanks! will fix this soon

**Comment by ingoradatz** [comment]
unsurprisingly it's the same in the ios app
