### ISSUE TITLE
android play store still at 1.11

### ISSUE THREAD

**Issue by jmarca** [mikeal/gatherbugs#65]
no update yet on Android (via Google Play).

**Comment by max-mapper** [comment]
thats just versioning differences (my bad), 1.11 on android is in fact the new release (last major release was in august). next time I release an android update i'll bump up the version to match iOS. thanks!

**Comment by jmarca** [comment]
okay.  sorry for the noise (your twitter reply said the same thing but I didn't understand the meaning).

I have issues with the current version on my tablet, but I didn't want to start reporting them with an old version.

Now that I know I'm up-to-date, I'll post away.
