### ISSUE TITLE
Android: Can use facebook's android APIs to avoid forcing user to retype password

### ISSUE THREAD

**Issue by apage43** [mikeal/gatherbugs#7]
If you use Facebook's Android SDK to do auth, and the user has the facebook app installed, they'll just be asked if they want to authorize your app instead of requiring them to login inside a webview.

https://developers.facebook.com/docs/reference/androidsdk/authentication/

**Comment by mikeal** [comment]
we do that on iOS. i think @maxogden said something about the SDK not working with latest Android.

**Comment by apage43** [comment]
Voxer's app has it working on Android 4.1.1 for me, maybe you could ask how they got it working.

**Comment by mikeal** [comment]
will do. we'll probably have to go over there some day and beg to use their devices for testing anyway :)

**Comment by max-mapper** [comment]
hmm weird i couldnt get the fb android sdk to compile under jellybean. will definitely have to ask voxer

**Comment by apage43** [comment]
Mm, well their app is probably -compiled- against an older SDK version. There at least aren't -runtime- issues with it. If I have some time I might poke around and see if I can't figure out what breaks it with the 4.1 SDK.
