### ISSUE TITLE
Android: Pressing location callout should use native maps apps

### ISSUE THREAD

**Issue by apage43** [mikeal/gatherbugs#8]
Right now if I press a location I get the mobile version of google maps trapped in the web view. Would be nice if it opened in Maps (or whatever my default mapping app is) so I could navigate to whatever shindig.

Should be able to open the native map app is by just firing off an ACTION_VIEW intent with the loc: URI.

http://drop.crate.im/2012-07-17_22.29.17-20120717-224110.png

**Comment by max-mapper** [comment]
ooh good idea

**Comment by max-mapper** [comment]
wait, I lied. I only fixed it on iOS. reopening

**Comment by max-mapper** [comment]
fixed https://gist.github.com/4151806
