### ISSUE TITLE
App state is unstable upon retuning to the app after placing it in the background

### ISSUE THREAD

**Issue by ruzz311** [mikeal/gatherbugs#9]
_Galaxy Nexus 4.0.4_

It's very common for me to move apps to the background to quickly look up something before posting.  

For Example:  
- Start a post (to twitter, facebook, or in this case gather)
- Realize I want to be witty and post a link in the description
- Put the app in the background by clicking the home button
- Copy the url: http://www.youtube.com/watch?v=0JElywbkSbY 
- _Point of Error_: Attempt to enter the app and paste the awesome link in the "where" input with a humorous remark.  This has happened almost every time I've left the app and come back, even on other screens (ie. map view)
- _Expected_: the post I started would still be available
- _Result_: My invite, which was almost complete except the crucial link in the header had closed and I was back at the "dashboard" where I was being prompted to add an event again because I had no available events in my proximity. (Kansas City on a Tuesday is not hoppin')

**Comment by mikeal** [comment]
This works in iOS. For some reason, on Android, returning to the app dumps us back in to the initial state.

**Comment by max-mapper** [comment]
thanks for the awesomely thorough description, this helps a lot. I may need to persist state manually
